### ISSUE TITLE
How to compile to exe?

### ISSUE THREAD

**Issue by me7** [HeapVoid/bimba#1]
e.g. I have index.imba and index.ts which both of them only have `console.log(42)`

- for index.ts file i can do `bun build --compile index.ts` to get index.exe and run fine
- for index.imba after `bun build --compile index.imba` the exe i've got run and nothing happen

**Comment by HeapVoid** [comment]
First you need to compile .imba file to .js and than compile this .js file. 
1. ```bunx bimba src/index.imba --outdir public```
2. ```bun build --compile public/index.js```
